import { StyleSheet } from "react-native";

export const AppStyles = StyleSheet.create({
  parent: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  topContainer: {
    display: "flex",
    width: "100%",
    paddingBottom: 16,
    paddingTop: 64,
    paddingHorizontal: 12,
    backgroundColor: "white",
    shadowColor: "black",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 12,
  },
  input: {
    flex: 1,
    marginTop: 12,
    fontFamily: "DMSans-Regular",
    fontSize: 16,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "rgba(0, 0, 0, 0.1)",
  },
  logo: {
    height: 56,
    width: 65,
  },
  header: {
    fontFamily: "DMSans-Regular",
    fontSize: 32,
    color: "black",
  },
  button: {
    alignSelf: "flex-end",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "black",
    marginLeft: 8,
  },
  buttonText: {
    fontFamily: "DMSans-Medium",
    fontSize: 16,
    color: "white",
  },
  galleryContainer: {
    flex: 1,
    width: "100%",
    position: "relative",
  },
  galleryImage: {
    width: "100%",
  },
  moreButton: {
    width: "100%",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "black",
    display: "flex",
    alignItems: "center",
    borderRadius: 10,
  },
  loadingContainer: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 4,
  },
});
